// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package main

type InXfmOutSpecSchemaJson struct {
	// input json schema definition
	In InXfmOutSpecSchemaJsonIn `json:"in,omitempty" yaml:"in,omitempty" mapstructure:"in,omitempty"`

	// transformer jsonata definition
	Jsonata *string `json:"jsonata,omitempty" yaml:"jsonata,omitempty" mapstructure:"jsonata,omitempty"`

	// output json schema definition
	Out InXfmOutSpecSchemaJsonOut `json:"out,omitempty" yaml:"out,omitempty" mapstructure:"out,omitempty"`
}

// input json schema definition
type InXfmOutSpecSchemaJsonIn map[string]interface{}

// output json schema definition
type InXfmOutSpecSchemaJsonOut map[string]interface{}
